spring.application.name = spring_mvc
spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=mvc;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=30042005
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#Cai nay la driver, chi chay khi chung ta da khai bao thu vien tai file pom
spring.jpa.hibernate.ddl-auto=update
# Dong nay giup khi chung ta thay entity trong java thi trong database no thay doi theo

# Security Config
s-mall.remember-me.key=S-Mall-Secret-Key-2024-@#!$
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# The hien cau lenh sql tai terminal thoi

#config spring security, username va password mac dinh
spring.security.user.name=nguyenthanhdat
spring.security.user.password=30042005